### ISSUE TITLE
which internal location it use 

### ISSUE THREAD

**Issue by idhirandar** [rkosegi/open-meteo-exporter#37]
which location should i mount to config.yaml

log output :- 

> ts=2024-01-13T21:16:23.931Z caller=main.go:76 level=info msg="Starting openmeteo_exporter" version="(version=, branch=, revision=unknown)" config=config.yaml
> 
> ts=2024-01-13T21:16:23.931Z caller=main.go:79 level=info msg="Build context" build_context="(go=go1.19.13, platform=linux/amd64, user=, date=, tags=unknown)"
> panic: open config.yaml: no such file or directory
> 
> goroutine 1 [running]:
main.main()
	/workspace/main.go:83 +0xba5`

**Comment by rkosegi** [comment]
Config is supposed to be in current working directory, which you can see in [Dockerfile](https://github.com/rkosegi/open-meteo-exporter/blob/main/Dockerfile#L15), it's set to '/'.

I'll add example to README
